### ISSUE TITLE
Can't Connect to MySQL Server for Tissue of Origin Example Dataset

### ISSUE THREAD

**Issue by mollee55** [Wittelab/orchid#8]
![jupyter-notebook11(cannotConnectToWitteLab-error)](https://user-images.githubusercontent.com/28766790/71132295-b2780600-21bc-11ea-9f87-7707aa3eb839.PNG)

Hi,

I have come across an error connecting to the MySQL server on `wittelab.ucf.edu` that was used for the Tissue of Origin Example dataset for the Orchid software when I tried to run it in the jupyter notebook for performing Machine Learning as specified in the wiki. I have attached a screenshot of my error message. Please let me know if there is any way of resolving this issue. Thanks!

**Comment by ccario83** [comment]
I'm not sure about the source of the original issue (sorry for the _very_ delayed response!), but [John Witte](https://profiles.stanford.edu/john-witte) and his lab have moved to Stanford, and the UCSF server hosting this database has been shut down permanently. The database, however, is still available as a dump file which I can provide upon request, if you are still needing it and are comfortable setting up your own MySQL server.

**Comment by mollee55** [comment]
Hi, thank you for your reply. This was for a class I was taking in graduate school, but I have since graduated. I will not be needing the database anymore. Thanks!
